[settings]
summary = ["Cloudflare-ECH", "Meta", "X-Twitter", "Telegram"]
user_agent = "Mozilla/5.0 (X11; Linux x86_64; ru-RU) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.208 Safari/537.36"
bgp_url = "https://bgp.tools/table.txt"

[services.Cloudflare-ECH]
type = "url"
v4_url = ["https://www.cloudflare.com/ips-v4"]
v6_url = ["https://www.cloudflare.com/ips-v6"]

[services.Cloudflare-ALL]
type = "asn"
asn = [13335, 132892, 209242, 139242, 203898, 394536, 395747, 14789, 12731, 174, 18450, 23352, 36351, 133877, 202623]

[services.Discord]
type = "url"
v4_url = ["https://iplist.opencck.org/?format=text&data=cidr4&site=discord.gg&site=discord.media", "https://raw.githubusercontent.com/GhostRooter0953/discord-voice-ips/refs/heads/master/voice_domains/discord-voice-ip-list"]
v6_url = ["https://iplist.opencck.org/?format=text&data=cidr6&site=discord.gg&site=discord.media"]

[services.Telegram]
type = "single_url"
url = ["https://core.telegram.org/resources/cidr.txt"]

[services.Meta]
type = "asn"
asn = [32934, 63293]

[services.X-Twitter]
type = "asn"
asn = 13414

[services.Hetzner]
type = "asn"
asn = 24940

[services.OVH]
type = "asn"
asn = 16276

[services.Amazon]
type = "asn"
asn = [16509, 14618, 8987, 46489, 21664, 7224, 264167, 274698, 36263, 801, 19047, 62785]

[services.DigitalOcean]
type = "asn"
asn = [14061, 393406, 46652]

[services.Akamai]
type = "asn"
asn = [20940, 32787, 63949, 12222, 200005, 35994, 24319, 34164, 16625, 26008, 31108, 21342, 17204, 49846, 35204, 213120, 18717, 393560, 33905, 393234, 31984]

[services.Google]
type = "asn"
asn = 15169

[services.Contabo]
type = "asn"
asn = 51167

[services.Scaleway]
type = "asn"
asn = 12876

[services.DataCamp-CDN77]
type = "asn"
asn = 60068

[services.Constant]
type = "asn"
asn = 20473

[services.Oracle]
type = "asn"
asn = [31898, 54253, 15519, 11049, 1218, 1219, 46558, 14544, 11506, 18916, 4184, 206209, 1216, 20054, 1217, 23885, 1215, 38538, 20037, 136025, 6142, 395010, 138207, 393773, 11479]